### PR TITLE
Add image above each section

### PR DESCRIPTION
**Pull request by TartanLlama**
Have a look and see what you folks think. Open to other suggestions for how to break up the text some more.

### CODE REVIEW

**Comment by davidtwco** [comment]
I like it, but it doesn't work great on the final few sections where there isn't much content - the image is visible multiple times in the viewport.

**Comment by davidtwco** [comment]
Perhaps inclusion of annotated images of the deck, or of a table with players around it could help illustrate points?

**Comment by TartanLlama** [comment]
Yeah, I agree about the final few sections. Maybe if we merged the contributors section with the license and attribution section it'd look better.

Good idea on the deck and table. Not sure what the best way to create the table image would be.

**Comment by davidtwco** [comment]
I'll take a shot at working one together in the style of the other artwork.

**Comment by TartanLlama** [comment]
Oh wow, adding the title image works really well.

**Comment by davidtwco** [comment]
I think the font next to the title image should change, the Secret Hitler website uses a mix of the rounded font that we use throughout and another non-rounded font for some of the larger headings like "FAQ". I don't think the rounded font looks great at that size.

**Comment by TartanLlama** [comment]
Unfortunately the other font they use isn't free. I make the title uppercase which looks a bit better.

**Comment by TartanLlama** [comment]
Some pretty suspect Javascript to split up the page and add a gun image, but I think it looks pretty good.

**Comment by davidtwco** [comment]
That looks really good, however, you're right in that the Javascript is starting to get a little bit out there.

I'd recommend splitting the content up into a [collection](https://jekyllrb.com/docs/collections/) - say, named `chapters` - and setting it such that [items in the collection aren't output into their own pages](https://jekyllrb.com/docs/collections/#step3) and then, using attributes on the collection, you can define which chapters have images below them - ie. an `image_below: gun`.

Then in the template for the index page, just iterate over the [items in the collection](https://jekyllrb.com/docs/collections/#liquid-attributes), checking for attributes and [including partials](http://jekyllrb.com/docs/templates/#includes) that match the name of the image attribute, if there is one. Would result in a much cleaner result. I'd be happy to do this sometime tomorrow unless you want to take a shot at it.

**Comment by TartanLlama** [comment]
That sounds like a good idea, feel free to have a bash at it!

**Comment by davidtwco** [comment]
Re-opening this since #53 merged into this branch.

**Pull request merged**
